theme: jekyll-theme-cayman
# show_edit_on_github: false
# github:
#   is_project_page: false
github:
  zip_url: https://github.com/bettygong/DSC180B-popularity-bias-in-Netflix-dataset.git
title: Handel Popularity Bias in Recommender System
description: Authors - Ziling Gong, Yihan Xue, Jiawei Wang